### PR TITLE
Migrate to Firebase Crashlytics from Fabric Crashlytics

### PR DESCRIPTION
**Pull request by vickydlion**
## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [1] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation  changes
- [ ] Other... Please describe:

## PR Checklist
For bug fixes / features, please check if your PR fulfills the following requirements:

- [1] Testing has been carried out for the changes have been added
- [ ] Regression testing has been carried out for existing functionality
- [ ] Docs have been added / updated

## What is the purpose of this PR?
Upgraded to Firebase crashlytics from fabric crashlytics.

## Does this PR introduce a breaking change?
- [ ] Yes
- [1] No

## Other information

### CODE REVIEW

**Comment by dpa99c** [comment]
Thanks for this @vickydlion, I'll give it a regression test ASAP

**Comment by Roshankd1** [comment]
thank you for this @vickydlion

**Comment by giuale88** [comment]
@vickydlion  great

**Comment by vickydlion** [comment]
Cheers to Everyone 👍

**Comment by aranjan** [comment]
Nice one @vickydlion, thanks for your contribution.

**Comment by dpa99c** [comment]
I've made [a commit based on this PR](https://github.com/dpa99c/cordova-plugin-firebasex/commit/d6c60a2e1a32bb9096b59fc83a73a4c335cc893e) which is currently on the dev branch. 

I've successfully tested on iOS but currently not seeing any crash data for Android using the new Firebase Crashlytics implementation.
If someone else could also give the dev branch and test and confirm if they see crashlytics data for Android, that'd be great.

To install the plugin direct from the dev branch:

    cordova plugin add https://github.com/dpa99c/cordova-plugin-firebasex#dev

Will close this PR now as it's essentially merged - thanks again @vickydlion

**Comment by Roshankd1** [comment]
@dpa99c quick question, in case of Ionic app, could we continue using "@ionic-native/firebase-x": "^5.26.0"
Thank you again.

**Comment by Roshankd1** [comment]
@vickydlion  Hey Vivek, I am not seeing crash reports for Android. Is it the same for you?

**Comment by stegithub** [comment]
> I've made [a commit based on this PR](https://github.com/dpa99c/cordova-plugin-firebasex/commit/d6c60a2e1a32bb9096b59fc83a73a4c335cc893e) which is currently on the dev branch.
> 
> I've successfully tested on iOS but currently not seeing any crash data for Android using the new Firebase Crashlytics implementation.
> If someone else could also give the dev branch and test and confirm if they see crashlytics data for Android, that'd be great.
> 
> To install the plugin direct from the dev branch:
> 
> ```
> cordova plugin add https://github.com/dpa99c/cordova-plugin-firebasex#dev
> ```
> 
> Will close this PR now as it's essentially merged - thanks again @vickydlion

Is it merged in production version? Or when will it be merged? Thanks for your work

**Comment by Roshankd1** [comment]
@dpa99c Hey Dave, any suggestions here, in iOS I am getting this error while trying out this merge.

`Firebase Installation registration failed for app with name: __FIRAPP_DEFAULT, error:
The server responded with an error: 
 - URL: https://firebaseinstallations.googleapis.com/v1/projects/my-app-prod/installations/ 
 - HTTP status code: 403 
 - Response body: {
  "error": {
    "code": 403,
    "message": "Requests to this API firebaseinstallations.googleapis.com method google.firebase.installations.v1.FirebaseInstallationsService.CreateInstallation are blocked.",
    "status": "PERMISSION_DENIED",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.Help",
        "links": [
          {
            "description": "Google developer console API key",
            "url": "https://console.developers.google.com/project/561605196520/apiui/credential"
          }
        ]
      }
    ]
  }
}
`

**Pull request closed without merging**
