### PR TITLE
Update AppDelegate+FirebasePlugin.m

### PR DESCRIPTION
**Pull request by souly1**
Seems like UNUserNotificationCenter is a singleton thus setting its delegate in the cordova-plugin-local-notifications is still available during initialization of this plugin, thus we can keep its instance if if exists and call its handler if we fail

## PR Type
What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation  changes
- [ ] Other... Please describe:

## PR Checklist
Please check your PR fulfills the following requirements:

Bugfixes:
- [ ] Regression testing has been carried out using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to ensure the intended bug is fixed and no regression bugs have been inadvertently introduced.

New features/enhancements:
- [ ] Exhaustive testing has been carried out for the new functionality
- [ ] Regression testing has been carried out to ensure no existing functionality is adversely affected
- [ ] Documentation has been added / updated
- [ ] The [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) has been update to validate/demonstrate the new functionality.

## What is the purpose of this PR?

Make this plugin work with cordova local notifications plugin on iOS

## Does this PR introduce a breaking change?
- [ ] Yes
- [x ] No

## What testing has been done on the changes in the PR?

not extensive

## What testing has been done on existing functionality?

not extensive

## Other information
merge or not if you want, placing it here for so that others users at least have it as a reference

### CODE REVIEW

**Comment by BradCB** [comment]
I have tested this pr on an iPhone 7 ios: 14.3 with cordova-plugin-local-notification 0.9.0-beta.3. 

Local and remote notifications are working when the app is closed or running in the background. 

I changed the first isContentAvailable to a try catch to get the remote notificaiton to show when the app is running and open. I had to add this even when sending a payload with content-available = 1.

@try{
               isContentAvailable = [[aps objectForKey:@"content-available"] isEqualToNumber:[NSNumber numberWithInt:1]];
            }@catch (NSException *exception) {
               
            }

**Comment by BradCB** [comment]
Are local notifications working for the foreground for iOS? Mine isn't working anymore.

**Comment by Phoenix-Alpha** [comment]
@dpa99c, @souly1, @BradCB, does this PR resolves conflict between firebasex and local notification? I still have issue with iOS foreground remote notification. onMessageRecevied is never fired. Could you please confirm? Thanks in advance.

**Comment by jircdev** [comment]
Hi, I'm having the same problem. This PR could be integrated ? some solution? thanks in advance.

**Pull request merged**
