### PR TITLE
use FirebaseFirestore pre-compiled pod

### PR DESCRIPTION
**Pull request by ovaris**
Use pre-compiled version of Firebase Firestore pod to reduce build times on iOS.
Significantly reduces build times, please see https://github.com/invertase/firestore-ios-sdk-frameworks for further details!

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ x] Refactoring (no functional changes, no api changes)
- [ ] Documentation  changes
- [ ] Other... Please describe:

## Does this PR introduce a breaking change?
- [ ] Yes
- [x ] No

### CODE REVIEW

**Comment by ovaris** [comment]
Hmm, noticed this isn't actually working:
```
pod install     
Analyzing dependencies
[!] There are multiple dependencies with different sources for `Firebase` in `Podfile`:

- Firebase/Core (= 6.23.0)
- Firebase/Auth (= 6.23.0)
- Firebase/Messaging (= 6.23.0)
- Firebase/Performance (= 6.23.0)
- Firebase/RemoteConfig (= 6.23.0)
- Firebase/Firestore (from `https://github.com/invertase/firestore-ios-sdk-frameworks.git`, tag `6.23.0`)
```

**Comment by dpa99c** [comment]
Thanks, this is a good idea. I'll regression test when I get some time.

**Comment by ovaris** [comment]
Fixed by updating pod name, also had to upgrade my cocoapods version from 1.8.X to 1.9.x, after that iOS project compiles without errors,

**Comment by dpa99c** [comment]
I've tested this and it works great - brings my build time down from ~240s to ~60s.

However, as you say this requires `cocoapods@1.9` which is a breaking change.
So I'm wondering whether this justifies another major version bump or whether, since I've just bumped the major version to 10 for the Firebase Crashlytics migration, we just push it out in a patch/minor version release?

I'm also thinking to add a hook script to check the cocoapods version which will prevent lots of support issues being opened due to plugin users having old versions of cocoapods.

**Comment by dpa99c** [comment]
I've published this in `cordova-plugin-firebasex@10.1.0` - thanks again for the idea

**Pull request closed without merging**
