### PR TITLE
Cli build

### PR DESCRIPTION
**Pull request by boblepepeur**
## PR Type
What kind of change does this PR introduce?
I just add the feature to change the auth language of firebase
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuth#setLanguageCode(java.lang.String)

I also add a PR for ionic-native plugin, for test, you can use https://github.com/boblepepeur/ionic-native before they accept.

I make this PR relative to https://github.com/dpa99c/cordova-plugin-firebasex/issues/510

- [ ] Bugfix
- [X ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [X ] Documentation  changes
- [ ] Other... Please describe:

## PR Checklist
Please check your PR fulfills the following requirements:

Bugfixes:
- [ ] Regression testing has been carried out using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to ensure the intended bug is fixed and no regression bugs have been inadvertently introduced.

New features/enhancements:
- [X ] Exhaustive testing has been carried out for the new functionality
- [ ] Regression testing has been carried out to ensure no existing functionality is adversely affected
- [X] Documentation has been added / updated
- [ ] The [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) has been update to validate/demonstrate the new functionality.

## Does this PR introduce a breaking change?
- [ ] Yes
- [X ] No

## What testing has been done on the changes in the PR?

I change local on android & IOS, every thing is working

### CODE REVIEW

**Comment by dpa99c** [comment]
No need to merge this PR as I'll merge your PR from master to cli_build

**Comment by boblepepeur** [comment]
When do you will merge to cli_build ?

**Comment by dpa99c** [comment]
Just merged it

**Comment by boblepepeur** [comment]
Your forget to merge cordova-plugin-firebasex/www/firebase.js 

:-)
Thanks for your job !

**Comment by dpa99c** [comment]
oops, just fixed it - try now

**Comment by boblepepeur** [comment]
yep its working now, thanks

**Pull request closed without merging**
