### PR TITLE
Removed requirement of Android hooks

### PR DESCRIPTION
**Pull request by sagrawal31**
@dpa99c your thoughts on this, please.

### CODE REVIEW

**Comment by dpa99c** [comment]
@sagrawal31 Thanks, I'll give this a test and report back.

FYI I'm moving house next week so fairly busy packing my entire life into boxes right now but I will try to get back to you ASAP 😀

**Comment by dpa99c** [comment]
As I've outlined in #63, I've determined the cause of the uninstall issue and it's not related to the Android hook scripts removed by this PR. 
Therefore I'm not sure merging this PR is necessary unless it adds other benefits?

**Comment by dpa99c** [comment]
@sagrawal31 Is there any benefit to merging this PR now (since #63 was fixed by removing the `<resource-file>` to copy the dummy `google-services.json` to the Android project)?

I guess it's cleaner than using the hook scripts but I'm always nervous of using the `apply plugin` in non-root Gradle configs to due the possibility of version conflicts with other plugins...

**Comment by sagrawal31** [comment]
@dpa99c In my view, using custom gradle file will keep the repository clean and readable as Android developers (who even have bare knowledge) will be able to understand the gradle file.

But if you feel, there might be a chance in future of conflict then take the call and close this MR. We can revisit this in the future if needed.

**Comment by sagrawal31** [comment]
Thanks @dpa99c 😄

**Comment by dpa99c** [comment]
@sagrawal31  No worries - I had another look at this and decided your approach is less fragile than those hook scripts. If any issues arise due to the extra Gradle config, we'll tackle them as they come up.
I'm back from vacation/moving house now so I'll try to address the outstanding issues and do a new patch release in the next few days.

**Comment by sagrawal31** [comment]
I'm glad our thoughts are in sync. 👍 

By the way, I'm also back from vacation/moving to a new house.

**Pull request merged**
